//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmnistrativo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(AnuncioMetadata))]
    public partial class Anuncio
    {
        public int CodigoAnuncio { get; set; }
        public string Titulo { get; set; }
        public string CaminhoImagem { get; set; }
        public string Conteudo { get; set; }
        public DateTime DataPublicacao { get; set; }
        public string LoginCriacao { get; set; }
        public string StatusAprovacao { get; set; }
        public string UsuarioAprovacao { get; set; }
        public int CodigoCategoria { get; set; }
        public string DescricaoCategoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
