//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmnistrativo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using PortalAdmnistrativo.Models.Metadata;

    [MetadataType(typeof(BolaoMetadata))]
    public partial class Bolao
    {
        public Nullable<int> RankingBolao { get; set; }
        public string LoginUsuario { get; set; }
        public string NomeRazaoSocial { get; set; }
        public Nullable<int> Pontuacao { get; set; }
        public Nullable<int> RelativoPrimeiroColocado { get; set; }
        public Nullable<int> RelativoColocadoAnterior { get; set; }
    }
}
