//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmnistrativo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Anuncio> Anuncio { get; set; }
        public DbSet<Categoria> Categoria { get; set; }
        public DbSet<Cidade> Cidade { get; set; }
        public DbSet<Comentario> Comentario { get; set; }
        public DbSet<Grupo> Grupo { get; set; }
        public DbSet<Historia> Historia { get; set; }
        public DbSet<Jogo> Jogo { get; set; }
        public DbSet<Noticia> Noticia { get; set; }
        public DbSet<PalpiteJogo> PalpiteJogo { get; set; }
        public DbSet<PontuacaoBolao> PontuacaoBolao { get; set; }
        public DbSet<Selecao> Selecao { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Bolao> Bolao { get; set; }
        public DbSet<DesempenhoSelecao> DesempenhoSelecao { get; set; }
        public DbSet<Ingresso> Ingresso { get; set; }
    }
}
