//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmnistrativo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Anuncio> Anuncios { get; set; }
        public DbSet<Categoria> Categorias { get; set; }
        public DbSet<Cidade> Cidades { get; set; }
        public DbSet<Comentario> Comentarios { get; set; }
        public DbSet<Grupo> Grupoes { get; set; }
        public DbSet<Historia> Historias { get; set; }
        public DbSet<Jogo> Jogoes { get; set; }
        public DbSet<Noticia> Noticias { get; set; }
        public DbSet<PalpiteJogo> PalpiteJogoes { get; set; }
        public DbSet<PontuacaoBolao> PontuacaoBolaos { get; set; }
        public DbSet<Selecao> Selecaos { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<Bolao> Bolaos { get; set; }
        public DbSet<DesempenhoSelecao> DesempenhoSelecaos { get; set; }
        public DbSet<Ingresso> Ingressoes { get; set; }
        public DbSet<Rodada> Rodadas { get; set; }
    }
}
