//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmnistrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidade
    {
        public Cidade()
        {
            this.Jogoes = new HashSet<Jogo>();
        }
    
        public int CodigoCidade { get; set; }
        public string Nome { get; set; }
        public string UF { get; set; }
        public string CaminhoImagem { get; set; }
        public string NomeEstadio { get; set; }
        public Nullable<int> CapacidadeEstadio { get; set; }
        public string InformacoesEstadio { get; set; }
    
        public virtual ICollection<Jogo> Jogoes { get; set; }
    }
}
