//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmnistrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int CodigoComentario { get; set; }
        public string Conteudo { get; set; }
        public string LoginCriacao { get; set; }
        public string NomeLoginCriacao { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public string StatusAprovacao { get; set; }
        public string UsuarioAprovacao { get; set; }
        public int CodigoNoticia { get; set; }
    
        public virtual Noticia Noticia { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
