//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmnistrativo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using PortalAdmnistrativo.Models.Metadata;

    [MetadataType(typeof(GrupoMetadata))]
    public partial class Grupo
    {
        public int CodigoGrupo { get; set; }
        public string DescricaoGrupo { get; set; }
    
        public virtual Selecao Selecao { get; set; }
    }
}
