//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmnistrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingresso
    {
        public int CodigoJogo { get; set; }
        public string NomeCidade { get; set; }
        public string LocalVendaIngresso { get; set; }
        public int Rodada { get; set; }
        public int CodigoSelecaoA { get; set; }
        public string NomeSelecaoA { get; set; }
        public int CodigoSelecaoB { get; set; }
        public string NomeSelecaoB { get; set; }
        public System.DateTime DataHora { get; set; }
    }
}
