//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmnistrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        public int CodigoNoticia { get; set; }
        public string Titulo { get; set; }
        public Nullable<System.DateTime> DataPublicacao { get; set; }
        public string Categoria { get; set; }
        public string Conteudo { get; set; }
    }
}
