//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmnistrativo.Models
{
    using System;
    using System.Collections.Generic;
    using PortalAdmnistrativo.Models.Metadata;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(NoticiaMetadata))]
    public partial class Noticia
    {
        public Noticia()
        {
            this.Comentario = new HashSet<Comentario>();
        }
    
        public int CodigoNoticia { get; set; }
        public string Titulo { get; set; }
        public string CaminhoImagem { get; set; }
        public string Conteudo { get; set; }
        public System.DateTime DataPublicacao { get; set; }
        public string Autor { get; set; }
        public int CodigoCategoria { get; set; }
        public string DescricaoCategoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<Comentario> Comentario { get; set; }
    }
}
