//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmnistrativo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(PalpiteJogoMetadata))]
    public partial class PalpiteJogo
    {
        public int CodigoPalpite { get; set; }
        public int codigoJogo { get; set; }
        public string LoginUsuario { get; set; }
        public System.DateTime DataAposta { get; set; }
        public int PalpiteGolsSelecaoA { get; set; }
        public int PalpiteGolsSelecaoB { get; set; }
    
        public virtual Jogo Jogo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
