//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmnistrativo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(PontuacaoBolaoMetadata))]
    public partial class PontuacaoBolao
    {
        public int CodigoPontuacaoBolao { get; set; }
        public string LoginUsuario { get; set; }
        public string NomeRazaoSocial { get; set; }
        public Nullable<int> AcertosPlacarCompleto { get; set; }
        public Nullable<int> AcertosResultadoPlacarParcial { get; set; }
        public Nullable<int> AcertosResultado { get; set; }
        public Nullable<int> RankingBolao { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
