//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmnistrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rodada
    {
        public int Rodada1 { get; set; }
        public string Fase { get; set; }
        public int CodigoSelecao { get; set; }
        public string NomeSelecao { get; set; }
        public int CodigoGrupo { get; set; }
        public Nullable<int> Empates { get; set; }
        public Nullable<int> Vitorias { get; set; }
        public Nullable<int> Derrotas { get; set; }
        public Nullable<int> GolsRealizados { get; set; }
        public Nullable<int> GolsSofridos { get; set; }
    }
}
