//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmnistrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string Login { get; set; }
        public decimal CnpjCpf { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Telefone { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string Sexo { get; set; }
        public string Senha { get; set; }
    }
}
