//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmnistrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Anuncio = new HashSet<Anuncio>();
            this.Comentario = new HashSet<Comentario>();
            this.PalpiteJogo = new HashSet<PalpiteJogo>();
            this.PontuacaoBolao = new HashSet<PontuacaoBolao>();
        }
    
        public string LoginUsuario { get; set; }
        public decimal CpfCnpj { get; set; }
        public string NomeRazaoSocial { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string Sexo { get; set; }
        public string TipoPerfil { get; set; }
    
        public virtual ICollection<Anuncio> Anuncio { get; set; }
        public virtual ICollection<Comentario> Comentario { get; set; }
        public virtual ICollection<PalpiteJogo> PalpiteJogo { get; set; }
        public virtual ICollection<PontuacaoBolao> PontuacaoBolao { get; set; }
    }
}
