//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmnistrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Anuncios = new HashSet<Anuncio>();
            this.Comentarios = new HashSet<Comentario>();
            this.PalpiteJogoes = new HashSet<PalpiteJogo>();
            this.PontuacaoBolaos = new HashSet<PontuacaoBolao>();
        }
    
        public string LoginUsuario { get; set; }
        public decimal CpfCnpj { get; set; }
        public string NomeRazaoSocial { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string Sexo { get; set; }
        public string TipoPerfil { get; set; }
    
        public virtual ICollection<Anuncio> Anuncios { get; set; }
        public virtual ICollection<Comentario> Comentarios { get; set; }
        public virtual ICollection<PalpiteJogo> PalpiteJogoes { get; set; }
        public virtual ICollection<PontuacaoBolao> PontuacaoBolaos { get; set; }
    }
}
