//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmnistrativo.Resouces {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Anuncio {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Anuncio() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortalAdmnistrativo.Resouces.Anuncio", typeof(Anuncio).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho da Imagem.
        /// </summary>
        public static string CaminhoImagem {
            get {
                return ResourceManager.GetString("CaminhoImagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administração de Anúncios.
        /// </summary>
        public static string CasoUso {
            get {
                return ResourceManager.GetString("CasoUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Anuncio.
        /// </summary>
        public static string CodigoAnuncio {
            get {
                return ResourceManager.GetString("CodigoAnuncio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdo do Anúncio.
        /// </summary>
        public static string Conteudo {
            get {
                return ResourceManager.GetString("Conteudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Publicação.
        /// </summary>
        public static string DataPublicacao {
            get {
                return ResourceManager.GetString("DataPublicacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Criação.
        /// </summary>
        public static string LoginCriacao {
            get {
                return ResourceManager.GetString("LoginCriacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Anúncios.
        /// </summary>
        public static string pnlTituloExclusao {
            get {
                return ResourceManager.GetString("pnlTituloExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir Novo Anúncio.
        /// </summary>
        public static string pnlTituloInclusao {
            get {
                return ResourceManager.GetString("pnlTituloInclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Aprovação.
        /// </summary>
        public static string StatusAprovacao {
            get {
                return ResourceManager.GetString("StatusAprovacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo Anúncio.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário Aprovação.
        /// </summary>
        public static string UsuarioAprovacao {
            get {
                return ResourceManager.GetString("UsuarioAprovacao", resourceCulture);
            }
        }
    }
}
