//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmnistrativo.Resouces {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Geral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Geral() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortalAdmnistrativo.Resouces.Geral", typeof(Geral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string btnCancelar {
            get {
                return ResourceManager.GetString("btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string btnExcluir {
            get {
                return ResourceManager.GetString("btnExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir.
        /// </summary>
        public static string btnIncluir {
            get {
                return ResourceManager.GetString("btnIncluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar.
        /// </summary>
        public static string btnLimpar {
            get {
                return ResourceManager.GetString("btnLimpar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string btnPesquisar {
            get {
                return ResourceManager.GetString("btnPesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string btnSalvar {
            get {
                return ResourceManager.GetString("btnSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir selecionados.
        /// </summary>
        public static string chkExcluiSelecionados {
            get {
                return ResourceManager.GetString("chkExcluiSelecionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar todos.
        /// </summary>
        public static string chkMarcarTodos {
            get {
                return ResourceManager.GetString("chkMarcarTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há registros a serem exibidos.
        /// </summary>
        public static string grdGridVazio {
            get {
                return ResourceManager.GetString("grdGridVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuncios.
        /// </summary>
        public static string mnuGerenciarAnuncio {
            get {
                return ResourceManager.GetString("mnuGerenciarAnuncio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notícias e Comentários.
        /// </summary>
        public static string mnuGerenciarNoticias {
            get {
                return ResourceManager.GetString("mnuGerenciarNoticias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleções.
        /// </summary>
        public static string mnuGerenciarSelecao {
            get {
                return ResourceManager.GetString("mnuGerenciarSelecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente excluir o(s) registro(s) selecionado(s)?.
        /// </summary>
        public static string msgConfirmaExclusao {
            get {
                return ResourceManager.GetString("msgConfirmaExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string optSelecionarTodos {
            get {
                return ResourceManager.GetString("optSelecionarTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione.
        /// </summary>
        public static string optSelecioneAlgum {
            get {
                return ResourceManager.GetString("optSelecioneAlgum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string pnlTituloBusca {
            get {
                return ResourceManager.GetString("pnlTituloBusca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string pnlTituloEdicao {
            get {
                return ResourceManager.GetString("pnlTituloEdicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string pnlTituloExclusao {
            get {
                return ResourceManager.GetString("pnlTituloExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir.
        /// </summary>
        public static string pnlTituloInclusao {
            get {
                return ResourceManager.GetString("pnlTituloInclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados.
        /// </summary>
        public static string pnlTituloResultado {
            get {
                return ResourceManager.GetString("pnlTituloResultado", resourceCulture);
            }
        }
    }
}
