USE BRAZUCAS
GO

INSERT INTO Usuario VALUES ('ajmaia',1234567890,'Alexandre Jr. Maia','ajmaia@brazucas.com','1989-08-13','M','Administrador','')
GO

INSERT INTO Categoria VALUES ('Curiosidades', 1)
INSERT INTO Categoria VALUES ('Bolao', NULL)
INSERT INTO Categoria VALUES ('Resultados', 1)
INSERT INTO Categoria VALUES ('Hoteis', 0)
INSERT INTO Categoria VALUES ('Pousadas', 0)
GO

INSERT INTO Grupo VALUES ('A')
INSERT INTO Grupo VALUES ('B')
INSERT INTO Grupo VALUES ('C')
INSERT INTO Grupo VALUES ('D')
INSERT INTO Grupo VALUES ('E')
INSERT INTO Grupo VALUES ('F')
INSERT INTO Grupo VALUES ('G')
INSERT INTO Grupo VALUES ('H')
GO

INSERT INTO Historia VALUES (NULL, 'Uruguai', NULL, '../../Content/themes/images/historia/hst_uruguai.jpg', 16, NULL)
INSERT INTO Historia VALUES (NULL, 'México', NULL, '../../Content/themes/images/historia/hst_mexico.jpg', 15, NULL)
INSERT INTO Historia VALUES (NULL, 'África do Sul', NULL, '../../Content/themes/images/historia/hst_africadosul.jpg', 60, NULL)
INSERT INTO Historia VALUES (NULL, 'França', NULL, '../../Content/themes/images/historia/hst_franca.jpg', 17, NULL)
INSERT INTO Historia VALUES (NULL, 'Argentina', NULL, '../../Content/themes/images/historia/hst_argentina.jpg', 3, NULL)
INSERT INTO Historia VALUES (NULL, 'Coreia do Sul', NULL, '../../Content/themes/images/historia/hst_coriadosul.jpg', 47, NULL)
INSERT INTO Historia VALUES (NULL, 'Grécia', NULL, '../../Content/themes/images/historia/hst_grecia.jpg', 12, NULL)
INSERT INTO Historia VALUES (NULL, 'Nigéria', NULL, '../../Content/themes/images/historia/hst_nigeria.jpg', 30, NULL)
INSERT INTO Historia VALUES (NULL, 'Estados Unidos', NULL, '../../Content/themes/images/historia/hst_estadosunidos.jpg', 33, NULL)
INSERT INTO Historia VALUES (NULL, 'Inglaterra', NULL, '../../Content/themes/images/historia/hst_inglaterra.jpg', 4, NULL)
INSERT INTO Historia VALUES (NULL, 'Eslovênia', NULL, '../../Content/themes/images/historia/hst_eslovênia.jpg', 56, NULL)
INSERT INTO Historia VALUES (NULL, 'Argélia', NULL, '../../Content/themes/images/historia/hst_argelia.jpg', 34, NULL)
INSERT INTO Historia VALUES (NULL, 'Alemanha', NULL, '../../Content/themes/images/historia/hst_alemanha.jpg', 2, NULL)
INSERT INTO Historia VALUES (NULL, 'Gana', NULL, '../../Content/themes/images/historia/hst_gana.jpg', 20, NULL)
INSERT INTO Historia VALUES (NULL, 'Austrália', NULL, '../../Content/themes/images/historia/hst_australia.jpg', 39, NULL)
INSERT INTO Historia VALUES (NULL, 'Sérvia', NULL, '../../Content/themes/images/historia/hst_servia.jpg', 35, NULL)
INSERT INTO Historia VALUES (NULL, 'Holanda', NULL, '../../Content/themes/images/historia/hst_holanda.jpg', 8, NULL)
INSERT INTO Historia VALUES (NULL, 'Japão', NULL, '../../Content/themes/images/historia/hst_japao.jpg', 26, NULL)
INSERT INTO Historia VALUES (NULL, 'Dinamarca', NULL, '../../Content/themes/images/historia/hst_dinamarca.jpg', 25, NULL)
INSERT INTO Historia VALUES (NULL, 'Camarões', NULL, '../../Content/themes/images/historia/hst_camaroes.jpg', 79, NULL)
INSERT INTO Historia VALUES (NULL, 'Paraguai', NULL, '../../Content/themes/images/historia/hst_paraguai.jpg', 38, NULL)
INSERT INTO Historia VALUES (NULL, 'Eslováquia', NULL, '../../Content/themes/images/historia/hst_eslovaquia.jpg', 57, NULL)
INSERT INTO Historia VALUES (NULL, 'Nova Zelândia', NULL, '../../Content/themes/images/historia/hst_novazelandia.jpg', 88, NULL)
INSERT INTO Historia VALUES (NULL, 'Itália', NULL, '../../Content/themes/images/historia/hst_italia.jpg', 5, NULL)
INSERT INTO Historia VALUES (NULL, 'Brasil', NULL, '../../Content/themes/images/historia/hst_brasil.jpg', 18, NULL)
INSERT INTO Historia VALUES (NULL, 'Portugal', NULL, '../../Content/themes/images/historia/hst_portugal.jpg', 7, NULL)
INSERT INTO Historia VALUES (NULL, 'Costa do Marfim', NULL, '../../Content/themes/images/historia/hst_costadomarfim.jpg', 13, NULL)
INSERT INTO Historia VALUES (NULL, 'Coreia do Norte', NULL, '../../Content/themes/images/historia/hst_coreiadonorte.jpg', 102, NULL)
INSERT INTO Historia VALUES (NULL, 'Espanha', NULL, '../../Content/themes/images/historia/hst_espanha.jpg', 1, NULL)
INSERT INTO Historia VALUES (NULL, 'Chile', NULL, '../../Content/themes/images/historia/hst_chile.jpg', 22, NULL)
INSERT INTO Historia VALUES (NULL, 'Suíça', NULL, '../../Content/themes/images/historia/hst_suica.jpg', 14, NULL)
INSERT INTO Historia VALUES (NULL, 'Honduras', NULL, '../../Content/themes/images/historia/hst_honduras.jpg', 49, NULL)
GO

INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Uruguai', '../../Content/themes/images/bandeiras/flg_uruguai.gif',1, 'A', 1)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('México', '../../Content/themes/images/bandeiras/flg_mexico.gif', 1, 'A', 2)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Africa do Sul', '../../Content/themes/images/bandeiras/flg_africadosul.gif',1, 'A', 3)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('França', '../../Content/themes/images/bandeiras/flg_franca.gif', 1,'A', 4)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Argentina', '../../Content/themes/images/bandeiras/flg_argentina.gif', 2,'B', 5)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Coreia do Sul', '../../Content/themes/images/bandeiras/flg_coreiadosul.gif', 2,'B', 6)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Grécia', '../../Content/themes/images/bandeiras/flg_grecia.gif', 2,'B', 7)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Nigéria', '../../Content/themes/images/bandeiras/flg_nigeria.gif', 2,'B', 8)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Estados Unidos', '../../Content/themes/images/bandeiras/flg_estadosunidos.gif', 3,'C', 9)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Inglaterra', '../../Content/themes/images/bandeiras/flg_inglaterra.gif', 3,'C', 10)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Eslovênia', '../../Content/themes/images/bandeiras/flg_eslovenia.gif', 3,'C', 11)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Argélia', '../../Content/themes/images/bandeiras/flg_argelia.gif', 3, 'C', 12)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Alemanha', '../../Content/themes/images/bandeiras/flg_alemanha.gif', 4,'D', 13)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Gana', '../../Content/themes/images/bandeiras/flg_gana.gif', 4,'D', 14)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Austrália', '../../Content/themes/images/bandeiras/flg_australia.gif', 4,'D', 15)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Sérvia', '../../Content/themes/images/bandeiras/flg_servia.gif', 4,'D', 16)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Holanda', '../../Content/themes/images/bandeiras/flg_holanda.gif', 5,'E', 17)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Japão', '../../Content/themes/images/bandeiras/flg_japao.gif', 5,'E', 18)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Dinamarca', '../../Content/themes/images/bandeiras/flg_dinamarca.gif', 5,'E', 19)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Camarões', '../../Content/themes/images/bandeiras/flg_camaroes.gif', 5,'E', 20)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Paraguai', '../../Content/themes/images/bandeiras/flg_paraguai.gif', 6,'F', 21)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Eslováquia', '../../Content/themes/images/bandeiras/flg_eslovaquia.gif', 6,'F', 22)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Nova Zelândia', '../../Content/themes/images/bandeiras/flg_novazelandia.gif', 6,'F', 23)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Itália', '../../Content/themes/images/bandeiras/flg_italia.gif', 6,'F', 24)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Brasil', '../../Content/themes/images/bandeiras/flg_brasil.gif', 7, 'G', 25)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Portugal', '../../Content/themes/images/bandeiras/flg_portugal.gif', 7, 'G', 26)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Costa do Marfim', '../../Content/themes/images/bandeiras/flg_costadomarfim.gif', 7, 'G', 27)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Coria do Norte', '../../Content/themes/images/bandeiras/flg_coriadonorte.gif', 7, 'G', 28)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Espanha', '../../Content/themes/images/bandeiras/flg_espanha.gif', 8, 'H', 29)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Chile', '../../Content/themes/images/bandeiras/flg_chile.gif', 8, 'H', 30)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Suíça', '../../Content/themes/images/bandeiras/flg_suica.gif', 8, 'H', 31)
INSERT INTO Selecao (Nome,  CaminhoImagem, CodigoGrupo, DescricaoGrupo, CodigoHistoria) VALUES ('Honduras', '../../Content/themes/images/bandeiras/flg_honduras.gif', 8, 'H', 32)
GO

INSERT INTO Cidade VALUES('Belo Horizonte', 'MG', '../../Content/themes/images/bandeiras/fto_belohorizonte.jpg', 'Estádio Mineirão', 62547, 'PENDENTE: Inserir localização...')
INSERT INTO Cidade VALUES('Brasília', 'DF', '../../Content/themes/images/bandeiras/fto_brasilia.jpg', 'Estádio Nacional Mané Garrincha', 70064, 'PENDENTE: Inserir localização...')
INSERT INTO Cidade VALUES('Cuiabá', 'MT', '../../Content/themes/images/bandeiras/fto_cuiaba.jpg', 'Arena Pantanal', 42968, 'PENDENTE: Inserir localização...')
INSERT INTO Cidade VALUES('Curitiba', 'PR', '../../Content/themes/images/bandeiras/fto_curitiba.jpg', 'Arena da Baixada', 42456, 'PENDENTE: Inserir localização...')
INSERT INTO Cidade VALUES('Fortaleza', 'CE', '../../Content/themes/images/bandeiras/fto_fortaleza.jpg', 'Estádio Castelão', 64846, 'PENDENTE: Inserir localização...')
INSERT INTO Cidade VALUES('Manaus', 'AM', '../../Content/themes/images/bandeiras/fto_manaus.jpg', 'Arena Amazônas', 42374, 'PENDENTE: Inserir localização...')
INSERT INTO Cidade VALUES('Natal', 'RN', '../../Content/themes/images/bandeiras/fto_natal.jpg', 'Estádio das Dunas', 42086, 'PENDENTE: Inserir localização...')
INSERT INTO Cidade VALUES('Porto Alegre', 'RS', '../../Content/themes/images/bandeiras/fto_portoalegre.jpg', 'Estádio Beira-Rio', 51000, 'PENDENTE: Inserir localização...')
INSERT INTO Cidade VALUES('Recife', 'PE', '../../Content/themes/images/bandeiras/fto_recife.jpg', 'Arena Pernambuco', 44248, 'PENDENTE: Inserir localização...')
INSERT INTO Cidade VALUES('Rio de Janeiro', 'RJ', '../../Content/themes/images/bandeiras/fto_riodejaneiro.jpg', 'Estádio do Maracanã', 76804, 'PENDENTE: Inserir localização...')
INSERT INTO Cidade VALUES('Salvador', 'BA', '../../Content/themes/images/bandeiras/fto_salvador.jpg', 'Arena Fonte Nova', 48747, 'PENDENTE: Inserir localização...')
INSERT INTO Cidade VALUES('São Paulo', 'SP', '../../Content/themes/images/bandeiras/fto_saopaulo.jpg', 'Arena de São Paulo', 65807, 'PENDENTE: Inserir localização...')
GO

INSERT INTO Anuncio (Titulo, CaminhoImagem, Conteudo, DataPublicacao, LoginCriacao, CodigoCategoria, DescricaoCategoria) VALUES('Celta Nova Geração', '../../Content/Uploads/anuncio_1.jpg', 'Chevrolet, Conte comigo. Escolha seu novo celta.', '2013-04-01','ajmaia',6,'Patrocínio')
INSERT INTO Anuncio (Titulo, CaminhoImagem, Conteudo, DataPublicacao, LoginCriacao, CodigoCategoria, DescricaoCategoria) VALUES('Ga, ga, gagueira tem cura', '../../Content/Uploads/anuncio_2.jpg', 'Fonoaudiologia Anhembi Morumbi.', '2013-04-01','ajmaia',6,'Patrocínio')
INSERT INTO Anuncio (Titulo, CaminhoImagem, Conteudo, DataPublicacao, LoginCriacao, CodigoCategoria, DescricaoCategoria) VALUES('Anuncie conosco', '../../Content/Uploads/anuncio_3.jpg', 'Mostre sua idéia, demonstre sua marca... Venha anunciar conosco.', '2013-04-01','ajmaia',6,'Patrocínio')
INSERT INTO Anuncio (Titulo, CaminhoImagem, Conteudo, DataPublicacao, LoginCriacao, CodigoCategoria, DescricaoCategoria) VALUES('Pepsi', '../../Content/Uploads/anuncio_4.jpg', 'Refresque com essa idéia, beba refrescncia.... beba PEPSI!', '2013-04-01','ajmaia',6,'Patrocínio')
INSERT INTO Anuncio (Titulo, CaminhoImagem, Conteudo, DataPublicacao, LoginCriacao, CodigoCategoria, DescricaoCategoria) VALUES('Pedigre', '../../Content/Uploads/anuncio_5.jpg', 'Saúde para seus gatos.', '2013-04-01','ajmaia',6,'Patrocínio')
INSERT INTO Anuncio (Titulo, CaminhoImagem, Conteudo, DataPublicacao, LoginCriacao, CodigoCategoria, DescricaoCategoria) VALUES('Dell', '../../Content/Uploads/anuncio_6.jpg', NULL, '2013-04-01','ajmaia',6,'Patrocínio')
GO