-- Fase de Grupos
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (12, 'www.ingressorapido.com', 1, '2014-06-12 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (7, 'www.ingressorapido.com', 1, '2014-06-13 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (11, 'www.ingressorapido.com', 1, '2014-06-13 16:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (3, 'www.ingressorapido.com', 1, '2014-06-13 18:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (1, 'www.ingressorapido.com', 1, '2014-06-14 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (5, 'www.ingressorapido.com', 1, '2014-06-14 16:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (9, 'www.ingressorapido.com', 1, '2014-06-14 19:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (6, 'www.ingressorapido.com', 1, '2014-06-14 21:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (2, 'www.ingressorapido.com', 1, '2014-06-15 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (8, 'www.ingressorapido.com', 1, '2014-06-15 16:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (10, 'www.ingressorapido.com', 1, '2014-06-15 19:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (11, 'www.ingressorapido.com', 1, '2014-06-16 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (4, 'www.ingressorapido.com', 1, '2014-06-16 16:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (7, 'www.ingressorapido.com', 1, '2014-06-16 19:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (1, 'www.ingressorapido.com', 1, '2014-06-17 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (5, 'www.ingressorapido.com', 1, '2014-06-17 16:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (3, 'www.ingressorapido.com', 1, '2014-06-17 18:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (8, 'www.ingressorapido.com', 1, '2014-06-18 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (6, 'www.ingressorapido.com', 1, '2014-06-18 16:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (10, 'www.ingressorapido.com', 1, '2014-06-18 18:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (2, 'www.ingressorapido.com', 1, '2014-06-19 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (12, 'www.ingressorapido.com', 1, '2014-06-19 16:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (7, 'www.ingressorapido.com', 1, '2014-06-19 18:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (9, 'www.ingressorapido.com', 1, '2014-06-20 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (11, 'www.ingressorapido.com', 1, '2014-06-20 16:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (4, 'www.ingressorapido.com', 1, '2014-06-20 19:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (1, 'www.ingressorapido.com', 1, '2014-06-21 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (5, 'www.ingressorapido.com', 1, '2014-06-21 16:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (3, 'www.ingressorapido.com', 1, '2014-06-21 18:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (8, 'www.ingressorapido.com', 1, '2014-06-22 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (6, 'www.ingressorapido.com', 1, '2014-06-22 16:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (10, 'www.ingressorapido.com', 1, '2014-06-22 19:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (4, 'www.ingressorapido.com', 1, '2014-06-23 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (12, 'www.ingressorapido.com', 1, '2014-06-23 16:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (2, 'www.ingressorapido.com', 1, '2014-06-23 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (9, 'www.ingressorapido.com', 1, '2014-06-23 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (1, 'www.ingressorapido.com', 1, '2014-06-24 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (7, 'www.ingressorapido.com', 1, '2014-06-24 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (3, 'www.ingressorapido.com', 1, '2014-06-24 16:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (5, 'www.ingressorapido.com', 1, '2014-06-24 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (8, 'www.ingressorapido.com', 1, '2014-06-25 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (11, 'www.ingressorapido.com', 1, '2014-06-25 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (6, 'www.ingressorapido.com', 1, '2014-06-25 16:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (10, 'www.ingressorapido.com', 1, '2014-06-25 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (2, 'www.ingressorapido.com', 1, '2014-06-26 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (9, 'www.ingressorapido.com', 1, '2014-06-26 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (4, 'www.ingressorapido.com', 1, '2014-06-26 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (12, 'www.ingressorapido.com', 1, '2014-06-26 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (1, 'www.ingressorapido.com', 1, '2014-06-28 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (10, 'www.ingressorapido.com', 1, '2014-06-28 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (5, 'www.ingressorapido.com', 1, '2014-06-29 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (9, 'www.ingressorapido.com', 1, '2014-06-29 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (2, 'www.ingressorapido.com', 1, '2014-06-30 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (8, 'www.ingressorapido.com', 1, '2014-06-30 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (11, 'www.ingressorapido.com', 1, '2014-07-01 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (12, 'www.ingressorapido.com', 1, '2014-07-01 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (5, 'www.ingressorapido.com', 1, '2014-07-04 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (10, 'www.ingressorapido.com', 1, '2014-07-04 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (2, 'www.ingressorapido.com', 1, '2014-07-05 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (11, 'www.ingressorapido.com', 1, '2014-07-05 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (1, 'www.ingressorapido.com', 1, '2014-07-08 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (12, 'www.ingressorapido.com', 1, '2014-07-09 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (2, 'www.ingressorapido.com', 1, '2014-07-12 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (10, 'www.ingressorapido.com', 1, '2014-07-13 16:00')
-- Oitavas de Final
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (1, 'Belo Horizonte', 'www.ingressorapido.com', 1, '28/06/2014 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (10, 'Rio de Janeiro', 'www.ingressorapido.com', 1, '28/06/2014 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (5, 'Fortaleza', 'www.ingressorapido.com', 1, '29/06/2014 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (9, 'Recife', 'www.ingressorapido.com', 1, '29/06/2014 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (2, 'Brasilia', 'www.ingressorapido.com', 1, '30/06/2014 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (8, 'Porto Alegre', 'www.ingressorapido.com', 1, '30/06/2014 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (11, 'Salvador', 'www.ingressorapido.com', 1, '01/07/2014 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (12, 'São Paulo', 'www.ingressorapido.com', 1, '01/07/2014 13:00')
-- Quartas de Final
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (5, 'Fortaleza', 'www.ingressorapido.com', 1, '04/07/2014 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (10, 'Rio de Janeiro', 'www.ingressorapido.com', 1, '04/07/2014 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (2, 'Brasilia', 'www.ingressorapido.com', 1, '05/07/2014 13:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (11, 'Salvador', 'www.ingressorapido.com', 1, '05/07/2014 17:00')
--Semifinal
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (1, 'Belo Horizonte', 'www.ingressorapido.com', 1, '08/07/2014 17:00')
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (12, 'São Paulo', 'www.ingressorapido.com', 1, '09/07/2014 17:00')
-- Disputa 3º Lugar
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (2, 'Brasilia', 'www.ingressorapido.com', 1, '12/07/2014 17:00')
-- Final
INSERT INTO Jogo (CodigoCidade, NomeCidade, LocalVendaIngresso, Rodada, DataHora) VALUES (10, 'Rio de Janeiro', 'www.ingressorapido.com', 1, '13/07/2014 16:00')